/*
 * PrefsWindow.java
 *
 * Created on August 5, 2007, 8:58 AM
 */

package com.powersurgepub.urlunion;

  import com.powersurgepub.psdatalib.ui.*;
  import com.powersurgepub.psfiles.*;
  import com.powersurgepub.psutils.*;
  import com.powersurgepub.xos2.*;
  import javax.swing.*;

/**
 *
 * @author  hbowie
 */
public class PrefsWindow 
  extends javax.swing.JFrame
    implements WindowToManage {
  
  private URLMainFrame      mainFrame;

  private XOS               xos = XOS.getShared();
  
  private ProgramVersion    programVersion = ProgramVersion.getShared();
  
  private boolean           setupComplete = false;
  
  private CommonPrefs       commonPrefs;
  private FavoritesPrefs    favoritesPrefs;
  private FilePrefs         filePrefs = null;
  
  /** Creates new form PrefsWindow */
  public PrefsWindow(URLMainFrame mainFrame) {

    this.mainFrame = mainFrame;
    initComponents();
    
    this.setTitle (Home.getShared().getProgramName() + " Preferences");
    this.setBounds (100, 100, 600, 400);

    commonPrefs = CommonPrefs.getShared();
    prefsTabs.addTab("General", commonPrefs);
    
    favoritesPrefs = new FavoritesPrefs (mainFrame);
    prefsTabs.addTab("Favorites", favoritesPrefs);
    
    setupComplete = true;
  }
  
  public void setFilePrefs(FilePrefs filePrefs) {
    this.filePrefs = filePrefs;
    prefsTabs.addTab("Files", filePrefs);
  }

  public void savePrefs() {
    commonPrefs.savePrefs();
    favoritesPrefs.savePrefs();
    if (filePrefs != null) {
      filePrefs.savePrefs();
    }
  }

  public FavoritesPrefs getFavoritesPrefs() {
    return favoritesPrefs;
  }
  
  public JTabbedPane getPrefsTabs() {
    return prefsTabs;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    prefsTabs = new javax.swing.JTabbedPane();

    setMinimumSize(new java.awt.Dimension(400, 300));
    setPreferredSize(new java.awt.Dimension(400, 30));
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentHidden(java.awt.event.ComponentEvent evt) {
        formComponentHidden(evt);
      }
    });
    getContentPane().add(prefsTabs, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
  WindowMenuManager.getShared().hide(this);
}//GEN-LAST:event_formComponentHidden
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane prefsTabs;
  // End of variables declaration//GEN-END:variables
  
}
